CC = g++
CFLAGS = -Wall -Werror -Wextra --std=c++17

all:

clean:

test:

s21_matrix_oop.a:

gcov_report:

valgrind:

cppcheck:
	cppcheck --enable=all --suppress=missingIncludeSystem *.cpp *.h

clang_format:
	clang-format -style=Google -n *.cpp *.h
	clang-format -style=Google -i *.cpp *.h